# Site settings
title: Sascha Bienert
email: sascha@twiddlefactor.de
description: > # this means to ignore newlines until "baseurl:"
  iOS-Developer
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: SaschaBienert
github_username:  jekyll

# Build settings
markdown: kramdown
